#!/bin/sh

cat <<EOF > /etc/nginx/nginx.conf
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                      '\$status \$body_bytes_sent "\$http_referer" '
                      '"\$http_user_agent" "\$http_x_forwarded_for"';

    access_log  /dev/stdout  main;
    error_log  /dev/stderr  notice;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

stream {
    upstream backend {
        server ${SERVER_IP}:${SERVER_PORT};
    }

    server {
        listen     25565;
        proxy_pass backend;
    }

    server {
        listen     ${SERVER_PORT};
        proxy_pass backend;
    }
}
EOF

cat <<EOF > /etc/nginx/conf.d/default.conf
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html index.htm;
    location / {
        try_files \$uri \$uri/ /index.html;
    }
    location /health {
        return 200;
    }
}
server {
    listen 80;
    server_name ${MAP_HOSTNAME};
    index index.html index.htm;
    location / {
        proxy_pass http://${SERVER_IP}:${MAP_PORT};
        proxy_redirect off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        break;
    }
}
EOF

exec nginx -g 'daemon off;'
